<?php

namespace Container0rSehCD;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8nUclwF.Symfony\Component\BrowserKit\Request' shared service.
     *
     * @return \Symfony\Component\BrowserKit\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.8nUclwF": it references class "Symfony\\Component\\BrowserKit\\Request" but no such service exists.');
    }
}
