<?php

namespace ContainerLt0NAp4;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NBEpF4nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nBEpF4n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nBEpF4n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\PropertyRepository', 'getPropertyRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\PropertyRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
