#services:
#  recaptcha.type:
#    class: Grafikart\RecaptchaBundle\Type\RecaptchaSubmitType
#    tags: ['form.type']
#    arguments:
#      $key: ''

#recaptcha: 
#  key: 6Lci4gIeAAAAAOCNPbFSQ19Lk1-vLwcp4uIOjqY1
#  secret: 6Lci4gIeAAAAABVpIv_iXPsm6OOd3Cb-gsT1Awph