<?php

namespace ContainerX0LW99d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPropertyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Sc2CSvO.App\Entity\Property' shared service.
     *
     * @return \App\Entity\Property
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Sc2CSvO": it references class "App\\Entity\\Property" but no such service exists.');
    }
}
