<?php

namespace ContainerOvmmsZv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kpg3j4eService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Kpg3j4e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Kpg3j4e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'optionRepository' => ['privates', 'App\\Repository\\OptionRepository', 'getOptionRepositoryService', true],
        ], [
            'optionRepository' => 'App\\Repository\\OptionRepository',
        ]);
    }
}
