<?php

namespace ContainerNWzUkNa;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kdg0RTXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Kdg0RTX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Kdg0RTX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\AdminAgenceController::delete' => ['privates', '.service_locator.YbcZo0s', 'get_ServiceLocator_YbcZo0sService', true],
            'App\\Controller\\Admin\\AdminAgenceController::edit' => ['privates', '.service_locator.YbcZo0s', 'get_ServiceLocator_YbcZo0sService', true],
            'App\\Controller\\Admin\\AdminAgenceController::index' => ['privates', '.service_locator.ZwUpJaQ', 'get_ServiceLocator_ZwUpJaQService', true],
            'App\\Controller\\Admin\\AdminOptionController::delete' => ['privates', '.service_locator.3N8ysha', 'get_ServiceLocator_3N8yshaService', true],
            'App\\Controller\\Admin\\AdminOptionController::edit' => ['privates', '.service_locator.3N8ysha', 'get_ServiceLocator_3N8yshaService', true],
            'App\\Controller\\Admin\\AdminOptionController::index' => ['privates', '.service_locator.1piRqeR', 'get_ServiceLocator_1piRqeRService', true],
            'App\\Controller\\Admin\\AdminPropertyController::delete' => ['privates', '.service_locator.45deAGo', 'get_ServiceLocator_45deAGoService', true],
            'App\\Controller\\Admin\\AdminPropertyController::edit' => ['privates', '.service_locator.45deAGo', 'get_ServiceLocator_45deAGoService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.tgVVt0z', 'get_ServiceLocator_TgVVt0zService', true],
            'App\\Controller\\PropertyController::index' => ['privates', '.service_locator..eHqkeB', 'get_ServiceLocator__EHqkeBService', true],
            'App\\Controller\\PropertyController::show' => ['privates', '.service_locator.45deAGo', 'get_ServiceLocator_45deAGoService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.riGN6sa', 'get_ServiceLocator_RiGN6saService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\Admin\\AdminAgenceController:delete' => ['privates', '.service_locator.YbcZo0s', 'get_ServiceLocator_YbcZo0sService', true],
            'App\\Controller\\Admin\\AdminAgenceController:edit' => ['privates', '.service_locator.YbcZo0s', 'get_ServiceLocator_YbcZo0sService', true],
            'App\\Controller\\Admin\\AdminAgenceController:index' => ['privates', '.service_locator.ZwUpJaQ', 'get_ServiceLocator_ZwUpJaQService', true],
            'App\\Controller\\Admin\\AdminOptionController:delete' => ['privates', '.service_locator.3N8ysha', 'get_ServiceLocator_3N8yshaService', true],
            'App\\Controller\\Admin\\AdminOptionController:edit' => ['privates', '.service_locator.3N8ysha', 'get_ServiceLocator_3N8yshaService', true],
            'App\\Controller\\Admin\\AdminOptionController:index' => ['privates', '.service_locator.1piRqeR', 'get_ServiceLocator_1piRqeRService', true],
            'App\\Controller\\Admin\\AdminPropertyController:delete' => ['privates', '.service_locator.45deAGo', 'get_ServiceLocator_45deAGoService', true],
            'App\\Controller\\Admin\\AdminPropertyController:edit' => ['privates', '.service_locator.45deAGo', 'get_ServiceLocator_45deAGoService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.tgVVt0z', 'get_ServiceLocator_TgVVt0zService', true],
            'App\\Controller\\PropertyController:index' => ['privates', '.service_locator..eHqkeB', 'get_ServiceLocator__EHqkeBService', true],
            'App\\Controller\\PropertyController:show' => ['privates', '.service_locator.45deAGo', 'get_ServiceLocator_45deAGoService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.riGN6sa', 'get_ServiceLocator_RiGN6saService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\Admin\\AdminAgenceController::delete' => '?',
            'App\\Controller\\Admin\\AdminAgenceController::edit' => '?',
            'App\\Controller\\Admin\\AdminAgenceController::index' => '?',
            'App\\Controller\\Admin\\AdminOptionController::delete' => '?',
            'App\\Controller\\Admin\\AdminOptionController::edit' => '?',
            'App\\Controller\\Admin\\AdminOptionController::index' => '?',
            'App\\Controller\\Admin\\AdminPropertyController::delete' => '?',
            'App\\Controller\\Admin\\AdminPropertyController::edit' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\PropertyController::index' => '?',
            'App\\Controller\\PropertyController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\AdminAgenceController:delete' => '?',
            'App\\Controller\\Admin\\AdminAgenceController:edit' => '?',
            'App\\Controller\\Admin\\AdminAgenceController:index' => '?',
            'App\\Controller\\Admin\\AdminOptionController:delete' => '?',
            'App\\Controller\\Admin\\AdminOptionController:edit' => '?',
            'App\\Controller\\Admin\\AdminOptionController:index' => '?',
            'App\\Controller\\Admin\\AdminPropertyController:delete' => '?',
            'App\\Controller\\Admin\\AdminPropertyController:edit' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\PropertyController:index' => '?',
            'App\\Controller\\PropertyController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
