home:
  path: /
  controller: App\Controller\HomeController::index

home2:
  path: /
  controller: App\Controller\HomeController::upcoins

shop:
  path: /shop
  controller: App\Controller\ShopController::index

#index:
#    path: /
#    controller: App\Controller\DefaultController::index

logout:
  path: /logout

register:
  path: /register
  controller: App\Controller\RegistrationController.php