home:
  path: /
  controller: App\Controller\HomeController::index

shop:
  path: /shop
  controller: App\Controller\ShopControllrt::index

#index:
#    path: /
#    controller: App\Controller\DefaultController::index

logout:
  path: /logout