<?php

namespace ContainerJxWJdNw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sc2CSvOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Sc2CSvO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Sc2CSvO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'property' => ['privates', '.errored..service_locator.Sc2CSvO.App\\Entity\\Property', NULL, 'Cannot autowire service ".service_locator.Sc2CSvO": it references class "App\\Entity\\Property" but no such service exists.'],
        ], [
            'property' => 'App\\Entity\\Property',
        ]);
    }
}
