<?php

namespace ContainerQxHLRSX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2NHzzGeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2NHzzGe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2NHzzGe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['privates', '.errored..service_locator.2NHzzGe.Doctrine\\Persistence\\ObjectManager', NULL, 'Cannot autowire service ".service_locator.2NHzzGe": it references interface "Doctrine\\Persistence\\ObjectManager" but no such service exists. You should maybe alias this interface to the existing "doctrine.orm.default_entity_manager" service.'],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'manager' => 'Doctrine\\Persistence\\ObjectManager',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
