<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWRbhHBa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWRbhHBa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWRbhHBa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWRbhHBa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWRbhHBa\App_KernelDevDebugContainer([
    'container.build_hash' => 'WRbhHBa',
    'container.build_id' => '25c69f74',
    'container.build_time' => 1639730591,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWRbhHBa');
