<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWRiJd8F\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWRiJd8F/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWRiJd8F.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWRiJd8F\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWRiJd8F\App_KernelDevDebugContainer([
    'container.build_hash' => 'WRiJd8F',
    'container.build_id' => 'a761ae27',
    'container.build_time' => 1661349195,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWRiJd8F');
