<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOvmmsZv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOvmmsZv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOvmmsZv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOvmmsZv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOvmmsZv\App_KernelDevDebugContainer([
    'container.build_hash' => 'OvmmsZv',
    'container.build_id' => 'a1335510',
    'container.build_time' => 1641808560,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOvmmsZv');
